### ISSUE TITLE
ImportError: No module named mediatools_swig

### ISSUE THREAD

**Issue by flaviomb** [osh/gr-mediatools#10]
after install meditools with cmake, I have faced with this message error after install mediatools 

Traceback (most recent call last):
```
    File "./source_alphabet.py", line 3, in <module>
    import mediatools
  File "/usr/local/lib/python2.7/dist-packages/mediatools/__init__.py", line 45, in <module>
    from mediatools_swig import *
ImportError: No module named mediatools_swig
```

Could anyone help me? I have no ideia what to do.

**Comment by pachpandepriti** [comment]
same problem
Using cmappertools v1.0.24.
Traceback (most recent call last):
  File "generate_RML2016.10a.py", line 3, in <module>
    from source_alphabet import source_alphabet
  File "/home/mesa/dataset/source_alphabet.py", line 3, in <module>
    import mediatools
ImportError: No module named mediatools

**Comment by dyang37** [comment]
Same problem here. Please help.

**Comment by LoveDLWujing** [comment]
Same problem here. Please help.
